### ISSUE TITLE
Unable to import Logger.

### ISSUE THREAD

**Issue by devashishsharma2302** [rapid7/le_node#153]
Hi, 
I just installed **le_node** from npm and could not import Logger. Here's the error that I get. 
![logger](https://user-images.githubusercontent.com/16999995/27860298-8c17d804-6199-11e7-9fde-257d9d8161c6.png)

I am running node v7.10.0.

**Comment by devashishsharma2302** [comment]
On some investigation I found out that this error is generating from index.js inside codependency package. May be bumping codependency version might solve this issue.

**Comment by bathos** [comment]
@devashishsharma2302 that looks like the Chrome console. This is a node library — you may be looking for [le_js](https://github.com/rapid7/le_js) which is the browserland lib.

**Comment by devashishsharma2302** [comment]
@bathos Yes I can use le_js,  but I am developing an application in reactJS with webpack and babel and preferred to install le_node via npm and ended up with this error. Is there a way I can use logentries with reactJS in  node environment?

**Comment by bathos** [comment]
No, it uses the node-specific tls, net, etc libs. These cannot be polyfilled in a browser. The errors you see are caused by transpiling node `require` into a bundler system’s require without the same semantics. That is surmountable, but once you fixed that you’d just end up with a different error on account of attempting to import tls etc.

**Comment by devashishsharma2302** [comment]
I see. Yes it makes sense. le_js would suit my use case. Thanks.

**Comment by devashishsharma2302** [comment]
@bathos I am a rookie in node development. Yes it is browser bundled code and I use a node server only while development, but I use node modules that I install via npm. I found le_js on npm now though and it works. [This](https://docs.logentries.com/docs/javascript)  doc doesn't include steps to install le_js from npm, so it made me think that le_node is the npm library for le_js.

**Comment by bathos** [comment]
Yeah, I’d agree that it’d be helpful if the site docs indicated that le_js is available through npm. I should note that I haven’t worked at Logentries for a few years, but I still sometimes answer questions since I’d authored this lib when I was there. It’s been improved a good amount since then, looks like mostly by one person whose github handle I don’t recognize, @stopal-r7, who I’m at-mentioning so that they can maybe pick up your documentation feedback given that, as this is a closed issue, it may not get noticed otherwise.

**Comment by devashishsharma2302** [comment]
@bathos Thanks for the support.
