### ISSUE TITLE
The following program never terminates

### ISSUE THREAD

**Issue by acrodrig** [rapid7/le_node#78]
I am using the latest version of `le_node`. The following program never terminates for me. It just hangs for minutes.

```js
var Logger = require("le_node");
var log = new Logger({ token: "<token>" });

log.err("Testing logger with error!");

log.end();
```

Thanks.

ACR

**Comment by bathos** [comment]
This may be a consequence of recent changes to the end() method. I'll look into it.

**Comment by bathos** [comment]
Indeed. It's not actually hanging (technically), it's just that the default connection duration before assuming no further logs are coming is several minutes, and I made an incorrect assumption about the connection drain event. Should be able to get a more rational behavior out of it if I dig into stream internals a little so that all parties may be happy with how end() works.

**Comment by forevermatt** [comment]
Until the root issue here is resolved, one workaround that seems to work is to manually close the connection once the ```finish``` event is fired (after manually calling ```end()```).

I know that the ```connection drain``` event is the one you are [supposed to listen for](https://github.com/logentries/le_node#drain-finish-pipe-and-unpipe) to know when the data has all been sent to Logentries, but in my limited testing, calling closeConnection() after the 'finish' event is fired has always allowed all of the data I tried to log to actually make it to Logentries.

Here's the a quick attempt at modifying your example code to use this approach:

    var Logger = require("le_node");
    var log = new Logger({ token: "<token>" });
    
    log.err("Testing logger with error!");
    
    log.once('finish', function() {
      log.closeConnection();
    });
    log.end();

**Comment by gearoidof-r7** [comment]
fixed
